version: "3"
services:
  server:
    container_name: todoapp-server
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  client:
    container_name: todoapp-client
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server

volumes:
  data:
